services:
  postgres:
    image: postgres:18
    container_name: studhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studhub_db
    ports:
      - "4444:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/data

volumes:
  pgdata:
